name: InstantBazzar
version: '${project.version}'
main: generalrs.instantbazzar.InstantBazzar
api-version: 1.19
authors: [ Generalrs, AsianousRice ]
description: A plugin th at allows the creation of a bazzar
